/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.quanghuyabc9.GUI.Home;

import com.quanghuyabc9.DTO.Conference;
import com.quanghuyabc9.GUI.Guess;
import com.quanghuyabc9.manager.MyApplication;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author quanghuyabc9
 */
public class CardViewItem extends javax.swing.JPanel {

    public static final int IMG_WIDTH = 430;
    public static final int IMG_HEIGHT = 163;
    public static final int MAX_LENGTH_TEXT = 60;

    private Conference conference;

    public CardViewItem(Conference _conference) {
        initComponents();
        conference = _conference;
        setData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlImageMain = new javax.swing.JPanel();
        lblImageMain = new javax.swing.JLabel();
        pnlTextMain = new javax.swing.JPanel();
        lblTimeTextMain = new javax.swing.JLabel();
        scrNameConferenceTextMain = new javax.swing.JScrollPane();
        txtNameConferenceTxtMain = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(430, 265));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        pnlImageMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlImageMain.setMinimumSize(new java.awt.Dimension(0, 160));
        pnlImageMain.setPreferredSize(new java.awt.Dimension(256, 163));
        pnlImageMain.setLayout(new java.awt.BorderLayout());

        lblImageMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImageMain.setMinimumSize(new java.awt.Dimension(256, 144));
        lblImageMain.setPreferredSize(new java.awt.Dimension(256, 144));
        pnlImageMain.add(lblImageMain, java.awt.BorderLayout.CENTER);

        pnlTextMain.setBackground(new java.awt.Color(255, 255, 255));

        lblTimeTextMain.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTimeTextMain.setForeground(new java.awt.Color(211, 74, 23));
        lblTimeTextMain.setText("Sun, Jul 19, 2020 12:00 ");
        lblTimeTextMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 20));

        scrNameConferenceTextMain.setBorder(null);
        scrNameConferenceTextMain.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrNameConferenceTextMain.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtNameConferenceTxtMain.setEditable(false);
        txtNameConferenceTxtMain.setBackground(new java.awt.Color(255, 255, 255));
        txtNameConferenceTxtMain.setColumns(20);
        txtNameConferenceTxtMain.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtNameConferenceTxtMain.setForeground(new java.awt.Color(58, 55, 80));
        txtNameConferenceTxtMain.setLineWrap(true);
        txtNameConferenceTxtMain.setRows(5);
        txtNameConferenceTxtMain.setText("RELIT! 2020:Bring. Your. Bdddddddddddđrave");
        txtNameConferenceTxtMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 10));
        scrNameConferenceTextMain.setViewportView(txtNameConferenceTxtMain);

        javax.swing.GroupLayout pnlTextMainLayout = new javax.swing.GroupLayout(pnlTextMain);
        pnlTextMain.setLayout(pnlTextMainLayout);
        pnlTextMainLayout.setHorizontalGroup(
            pnlTextMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTimeTextMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrNameConferenceTextMain)
        );
        pnlTextMainLayout.setVerticalGroup(
            pnlTextMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTextMainLayout.createSequentialGroup()
                .addComponent(lblTimeTextMain, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(scrNameConferenceTextMain, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTextMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlImageMain, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlImageMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlTextMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(pnlMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        if (conference != null) {
            Guess root = (Guess) SwingUtilities.getWindowAncestor(this);
            root.showPnlDetailConferenceMain(conference);
        }
    }//GEN-LAST:event_formMousePressed

    public final void setData() {
        if (conference != null) {
            Conference tmp1 = conference;
            Timestamp tmp = conference.getTimeStart();
            Date timeStartDate = new Date(conference.getTimeStart().getTime());
            SimpleDateFormat dateFormat = new SimpleDateFormat("EEE, MMM dd, yyyy h:mm a");
            String timeStartStr = dateFormat.format(timeStartDate);
            lblTimeTextMain.setText(timeStartStr);
            String nameConference = conference.getNameConference();
            if (nameConference.length() > MAX_LENGTH_TEXT) {
                nameConference = nameConference.substring(0, MAX_LENGTH_TEXT + 1);
                nameConference += "...";
            }
            txtNameConferenceTxtMain.setText(nameConference);
            String image = MyApplication.getLocalImagesPath() + conference.getImage();
            BufferedImage img = null;
            try {
                img = ImageIO.read(new File(image));
            } catch (Exception e) {
                img = null;
                //e.printStackTrace();
            }
            if (img != null) {

//                Image dimg = img.getScaledInstance(430, 163, Image.SCALE_SMOOTH);
                // creates output image
//                BufferedImage outputImage = new BufferedImage(475,
//                        182, img.getType());
//
//                // scales the input image to the output image
//                Graphics2D g2d = outputImage.createGraphics();
//                g2d.drawImage(img, 0, 0, 475, 182, null);
//                g2d.dispose();
                Image dimg = img.getScaledInstance(IMG_WIDTH, IMG_HEIGHT, Image.SCALE_AREA_AVERAGING);
                lblImageMain.setIcon(new ImageIcon(dimg));
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblImageMain;
    private javax.swing.JLabel lblTimeTextMain;
    private javax.swing.JPanel pnlImageMain;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlTextMain;
    private javax.swing.JScrollPane scrNameConferenceTextMain;
    private javax.swing.JTextArea txtNameConferenceTxtMain;
    // End of variables declaration//GEN-END:variables
}
