/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.quanghuyabc9.GUI.Home;

import com.quanghuyabc9.BUS.RegisteredConferenceBUS;
import com.quanghuyabc9.BUS.RegisteringConferenceBUS;
import com.quanghuyabc9.DTO.Conference;
import com.quanghuyabc9.DTO.RegisteredConference;
import com.quanghuyabc9.GUI.Guess;
import java.awt.Color;
import javax.swing.SwingUtilities;

/**
 *
 * @author quanghuyabc9
 */
public class ListViewItem01 extends javax.swing.JPanel {

    private Conference conference;

    public static final Color MOUSE_MOVED_PNL_COLOR = new Color(129, 131, 185);
    public static final Color MOUSE_EXITED_PNL_COLOR = new Color(255, 255, 255);

    public ListViewItem01(Conference _conference) {
        initComponents();
        conference = _conference;
        setData();
    }

    public final void setData() {
        if (conference != null) {
            String name = conference.getNameConference();
            String time = conference.getTimeStart().toString();
            String duration = conference.getDuration().toString();
            int nPeople = RegisteredConferenceBUS.getRegisterdConferencesOfConference(conference).size()
                    +  RegisteringConferenceBUS.getRegisteringConferencesOfConference(conference).size();
            String location = conference.getLocation().toString();
            lblNameValue.setText(name);
            lblTimeValue.setText(time);
            lblDuration.setText(duration);
            lblPeople.setText(String.valueOf(nPeople));
            lblLocation.setText(location);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblNameValue = new javax.swing.JLabel();
        lblTimeValue = new javax.swing.JLabel();
        lblDuration = new javax.swing.JLabel();
        lblPeople = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 25, 0, 0));
        setPreferredSize(new java.awt.Dimension(621, 50));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        setLayout(new java.awt.GridBagLayout());

        lblNameValue.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNameValue.setForeground(new java.awt.Color(51, 51, 51));
        lblNameValue.setText("Name value");
        lblNameValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lblNameValue.setPreferredSize(new java.awt.Dimension(0, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.weighty = 1.0;
        add(lblNameValue, gridBagConstraints);

        lblTimeValue.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTimeValue.setForeground(new java.awt.Color(51, 51, 51));
        lblTimeValue.setText("Time value");
        lblTimeValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lblTimeValue.setPreferredSize(new java.awt.Dimension(0, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.weighty = 1.0;
        add(lblTimeValue, gridBagConstraints);

        lblDuration.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDuration.setForeground(new java.awt.Color(51, 51, 51));
        lblDuration.setText("Duration value");
        lblDuration.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lblDuration.setPreferredSize(new java.awt.Dimension(0, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        add(lblDuration, gridBagConstraints);

        lblPeople.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPeople.setForeground(new java.awt.Color(51, 51, 51));
        lblPeople.setText("People value");
        lblPeople.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lblPeople.setPreferredSize(new java.awt.Dimension(0, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        add(lblPeople, gridBagConstraints);

        lblLocation.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLocation.setForeground(new java.awt.Color(51, 51, 51));
        lblLocation.setText("Location value");
        lblLocation.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        lblLocation.setPreferredSize(new java.awt.Dimension(0, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        add(lblLocation, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        if (conference != null) {
            Guess root = (Guess) SwingUtilities.getWindowAncestor(this);
            root.showPnlDetailConferenceMain(conference);
        }
    }//GEN-LAST:event_formMousePressed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        setBackground(MOUSE_MOVED_PNL_COLOR);
    }//GEN-LAST:event_formMouseMoved

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        setBackground(MOUSE_EXITED_PNL_COLOR);
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblNameValue;
    private javax.swing.JLabel lblPeople;
    private javax.swing.JLabel lblTimeValue;
    // End of variables declaration//GEN-END:variables
}
