/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.quanghuyabc9.GUI.Home;

import com.quanghuyabc9.DTO.Person;

/**
 *
 * @author quanghuyabc9
 */
public class ParticipantItem extends javax.swing.JPanel {

    private int order;
    private Person person;
    private String status;
    public ParticipantItem(int _order, Person _person, String _status) {
        person = _person;
        order = _order;
        status = _status;
        initComponents();
        setData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblOrder = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        setPreferredSize(new java.awt.Dimension(0, 50));
        setLayout(new java.awt.GridBagLayout());

        lblOrder.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblOrder.setForeground(new java.awt.Color(51, 51, 51));
        lblOrder.setText("Order");
        lblOrder.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        add(lblOrder, gridBagConstraints);

        lblUsername.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(51, 51, 51));
        lblUsername.setText("Username");
        lblUsername.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(lblUsername, gridBagConstraints);

        lblStatus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(46, 164, 79));
        lblStatus.setText("Status");
        lblStatus.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        add(lblStatus, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void setData() {
        lblOrder.setText(String.valueOf(order));
        lblUsername.setText(person.getUsername());
        lblStatus.setText(status);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblOrder;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
