/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.quanghuyabc9.GUI;

import com.quanghuyabc9.GUI.Management.ManageConference;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author quanghuyabc9
 */
public class Confirm extends javax.swing.JDialog {

    /**
     * Creates new form SignupError
     */
    public Confirm(java.awt.Frame parent, boolean modal, String msg) {
        super(parent, modal);
        initComponents();
        txtViewMsgMain.setText(msg);
    }
    
    private boolean delete = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlViewMsgMain = new javax.swing.JPanel();
        scrViewMsgMain = new javax.swing.JScrollPane();
        txtViewMsgMain = new javax.swing.JTextArea();
        pnlYesMain = new javax.swing.JPanel();
        lblYes = new javax.swing.JLabel();
        pnlNoMain = new javax.swing.JPanel();
        lblNo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pnlMain.setBackground(new java.awt.Color(237, 235, 233));

        pnlViewMsgMain.setBackground(new java.awt.Color(255, 255, 255));

        scrViewMsgMain.setBackground(new java.awt.Color(255, 255, 255));
        scrViewMsgMain.setBorder(null);

        txtViewMsgMain.setEditable(false);
        txtViewMsgMain.setBackground(new java.awt.Color(255, 255, 255));
        txtViewMsgMain.setColumns(20);
        txtViewMsgMain.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtViewMsgMain.setForeground(new java.awt.Color(46, 164, 79));
        txtViewMsgMain.setLineWrap(true);
        txtViewMsgMain.setRows(5);
        txtViewMsgMain.setText("Message");
        txtViewMsgMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 0, 20));
        scrViewMsgMain.setViewportView(txtViewMsgMain);

        javax.swing.GroupLayout pnlViewMsgMainLayout = new javax.swing.GroupLayout(pnlViewMsgMain);
        pnlViewMsgMain.setLayout(pnlViewMsgMainLayout);
        pnlViewMsgMainLayout.setHorizontalGroup(
            pnlViewMsgMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrViewMsgMain, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnlViewMsgMainLayout.setVerticalGroup(
            pnlViewMsgMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrViewMsgMain, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );

        pnlYesMain.setBackground(new java.awt.Color(46, 164, 79));
        pnlYesMain.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(46, 164, 79), 2, true));
        pnlYesMain.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlYesMainMouseMoved(evt);
            }
        });
        pnlYesMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlYesMainMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlYesMainMousePressed(evt);
            }
        });

        lblYes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblYes.setForeground(new java.awt.Color(255, 255, 255));
        lblYes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblYes.setText("Yes");

        javax.swing.GroupLayout pnlYesMainLayout = new javax.swing.GroupLayout(pnlYesMain);
        pnlYesMain.setLayout(pnlYesMainLayout);
        pnlYesMainLayout.setHorizontalGroup(
            pnlYesMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblYes, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
        );
        pnlYesMainLayout.setVerticalGroup(
            pnlYesMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblYes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlNoMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlNoMain.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(223, 220, 230), 2, true));
        pnlNoMain.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlNoMainMouseMoved(evt);
            }
        });
        pnlNoMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlNoMainMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlNoMainMousePressed(evt);
            }
        });

        lblNo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNo.setForeground(new java.awt.Color(51, 51, 51));
        lblNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNo.setText("No");

        javax.swing.GroupLayout pnlNoMainLayout = new javax.swing.GroupLayout(pnlNoMain);
        pnlNoMain.setLayout(pnlNoMainLayout);
        pnlNoMainLayout.setHorizontalGroup(
            pnlNoMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNo, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
        );
        pnlNoMainLayout.setVerticalGroup(
            pnlNoMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlViewMsgMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(0, 151, Short.MAX_VALUE)
                        .addComponent(pnlNoMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlYesMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlViewMsgMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlNoMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlYesMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlYesMainMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlYesMainMouseMoved
        // TODO add your handling code here:
        pnlYesMain.setBackground(Signin.MOUSE_MOVED_BTN_COLOR);
    }//GEN-LAST:event_pnlYesMainMouseMoved

    private void pnlYesMainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlYesMainMousePressed
        // TODO add your handling code here:
        delete = true;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_pnlYesMainMousePressed

    private void pnlYesMainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlYesMainMouseExited
        // TODO add your handling code here:
        pnlYesMain.setBackground(Signin.MOUSE_EXITED_BTN_COLOR);
    }//GEN-LAST:event_pnlYesMainMouseExited

    private void pnlNoMainMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNoMainMouseMoved
        // TODO add your handling code here:
        pnlNoMain.setBackground(ManageConference.MOUSE_MOVED_PNL_COLOR_2);
    }//GEN-LAST:event_pnlNoMainMouseMoved

    private void pnlNoMainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNoMainMousePressed
        // TODO add your handling code here:
        delete = false;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_pnlNoMainMousePressed

    private void pnlNoMainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNoMainMouseExited
        // TODO add your handling code here:
        pnlNoMain.setBackground(ManageConference.MOUSE_EXITED_PNL_COLOR_2);
    }//GEN-LAST:event_pnlNoMainMouseExited

    public boolean showDialog() {
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - getWidth()) / 2;
        final int y = (screenSize.height - getHeight()) / 2;
        setLocation(x, y);
        setVisible(true);
        setLocationRelativeTo(null);
        return delete;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblYes;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlNoMain;
    private javax.swing.JPanel pnlViewMsgMain;
    private javax.swing.JPanel pnlYesMain;
    private javax.swing.JScrollPane scrViewMsgMain;
    private javax.swing.JTextArea txtViewMsgMain;
    // End of variables declaration//GEN-END:variables
}
