/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.quanghuyabc9.GUI;

import com.quanghuyabc9.GUI.Management.ManageConference;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author quanghuyabc9
 */
public class EnrollError extends javax.swing.JDialog {

    public static final int ACTION_NONE = 0;
    public static final int ACTION_SIGNIN = 2;
    public static final int ACTION_SIGNUP = 1;
    public EnrollError(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        action = ACTION_NONE;
        initComponents();
    }

    private int action;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlViewMain = new javax.swing.JPanel();
        lblInfoMain = new javax.swing.JLabel();
        pnlSigninMain = new javax.swing.JPanel();
        lblSigninMain = new javax.swing.JLabel();
        pnlSignupMain = new javax.swing.JPanel();
        lblSinupMain = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Error");
        setResizable(false);

        pnlMain.setBackground(new java.awt.Color(237, 235, 233));

        pnlViewMain.setBackground(new java.awt.Color(255, 255, 255));

        lblInfoMain.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblInfoMain.setForeground(new java.awt.Color(255, 0, 0));
        lblInfoMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfoMain.setText("<html>You need to sign in before enrolling! If you dont have account, you can click sign up!<html>");
        lblInfoMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 25, 0, 25));

        javax.swing.GroupLayout pnlViewMainLayout = new javax.swing.GroupLayout(pnlViewMain);
        pnlViewMain.setLayout(pnlViewMainLayout);
        pnlViewMainLayout.setHorizontalGroup(
            pnlViewMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInfoMain, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
        );
        pnlViewMainLayout.setVerticalGroup(
            pnlViewMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInfoMain, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );

        pnlSigninMain.setBackground(new java.awt.Color(46, 164, 79));
        pnlSigninMain.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(46, 164, 79), 2, true));
        pnlSigninMain.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlSigninMainMouseMoved(evt);
            }
        });
        pnlSigninMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSigninMainMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlSigninMainMousePressed(evt);
            }
        });

        lblSigninMain.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSigninMain.setForeground(new java.awt.Color(255, 255, 255));
        lblSigninMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSigninMain.setText("Sign in");

        javax.swing.GroupLayout pnlSigninMainLayout = new javax.swing.GroupLayout(pnlSigninMain);
        pnlSigninMain.setLayout(pnlSigninMainLayout);
        pnlSigninMainLayout.setHorizontalGroup(
            pnlSigninMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSigninMain, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
        );
        pnlSigninMainLayout.setVerticalGroup(
            pnlSigninMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSigninMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlSignupMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlSignupMain.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(223, 220, 230), 2, true));
        pnlSignupMain.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlSignupMainMouseMoved(evt);
            }
        });
        pnlSignupMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSignupMainMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlSignupMainMousePressed(evt);
            }
        });

        lblSinupMain.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSinupMain.setForeground(new java.awt.Color(51, 51, 51));
        lblSinupMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSinupMain.setText("Sign up");

        javax.swing.GroupLayout pnlSignupMainLayout = new javax.swing.GroupLayout(pnlSignupMain);
        pnlSignupMain.setLayout(pnlSignupMainLayout);
        pnlSignupMainLayout.setHorizontalGroup(
            pnlSignupMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSinupMain, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
        );
        pnlSignupMainLayout.setVerticalGroup(
            pnlSignupMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSinupMain, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlSignupMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlSigninMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(pnlViewMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlViewMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlSignupMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlSigninMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlSigninMainMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSigninMainMouseMoved
        // TODO add your handling code here:
        pnlSigninMain.setBackground(Signin.MOUSE_MOVED_BTN_COLOR);
    }//GEN-LAST:event_pnlSigninMainMouseMoved

    private void pnlSigninMainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSigninMainMousePressed
        // TODO add your handling code here:
        action = ACTION_SIGNIN;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_pnlSigninMainMousePressed

    private void pnlSigninMainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSigninMainMouseExited
        // TODO add your handling code here:
        pnlSigninMain.setBackground(Signin.MOUSE_EXITED_BTN_COLOR);
    }//GEN-LAST:event_pnlSigninMainMouseExited

    private void pnlSignupMainMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSignupMainMouseMoved
        // TODO add your handling code here:
        pnlSignupMain.setBackground(ManageConference.MOUSE_MOVED_PNL_COLOR_2);
    }//GEN-LAST:event_pnlSignupMainMouseMoved

    private void pnlSignupMainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSignupMainMousePressed
        // TODO add your handling code here:
        action = ACTION_SIGNUP;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_pnlSignupMainMousePressed

    private void pnlSignupMainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSignupMainMouseExited
        // TODO add your handling code here:
        pnlSignupMain.setBackground(ManageConference.MOUSE_EXITED_PNL_COLOR_2);
    }//GEN-LAST:event_pnlSignupMainMouseExited

    public int showDialog() {
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - getWidth()) / 2;
        final int y = (screenSize.height - getHeight()) / 2;
        setLocation(x, y);
        setVisible(true);
        setLocationRelativeTo(null);
        return action;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblInfoMain;
    private javax.swing.JLabel lblSigninMain;
    private javax.swing.JLabel lblSinupMain;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlSigninMain;
    private javax.swing.JPanel pnlSignupMain;
    private javax.swing.JPanel pnlViewMain;
    // End of variables declaration//GEN-END:variables
}
