/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.quanghuyabc9.GUI;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author quanghuyabc9
 */
public class Error extends javax.swing.JDialog {

    List<String> errors;
    public Error(java.awt.Frame parent, boolean modal, List<String> _errors) {
        super(parent, modal);
        errors = _errors;
        initComponents();
        setData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlViewMain = new javax.swing.JPanel();
        lblErrorViewMain = new javax.swing.JLabel();
        scrListErrorViewMain = new javax.swing.JScrollPane();
        txtListErrorViewMain = new javax.swing.JTextArea();
        pnlOkMain = new javax.swing.JPanel();
        lblOkMain = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pnlMain.setBackground(new java.awt.Color(237, 235, 233));
        pnlMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 0, 10));

        pnlViewMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlViewMain.setPreferredSize(new java.awt.Dimension(260, 95));

        lblErrorViewMain.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblErrorViewMain.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorViewMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErrorViewMain.setText("Error");

        scrListErrorViewMain.setBorder(null);

        txtListErrorViewMain.setEditable(false);
        txtListErrorViewMain.setBackground(new java.awt.Color(255, 255, 255));
        txtListErrorViewMain.setColumns(20);
        txtListErrorViewMain.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtListErrorViewMain.setForeground(new java.awt.Color(255, 0, 0));
        txtListErrorViewMain.setLineWrap(true);
        txtListErrorViewMain.setRows(5);
        txtListErrorViewMain.setText("List errors");
        txtListErrorViewMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 0, 20));
        scrListErrorViewMain.setViewportView(txtListErrorViewMain);

        javax.swing.GroupLayout pnlViewMainLayout = new javax.swing.GroupLayout(pnlViewMain);
        pnlViewMain.setLayout(pnlViewMainLayout);
        pnlViewMainLayout.setHorizontalGroup(
            pnlViewMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblErrorViewMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrListErrorViewMain, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
        );
        pnlViewMainLayout.setVerticalGroup(
            pnlViewMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewMainLayout.createSequentialGroup()
                .addComponent(lblErrorViewMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrListErrorViewMain, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
        );

        pnlOkMain.setBackground(new java.awt.Color(46, 164, 79));
        pnlOkMain.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlOkMainMouseMoved(evt);
            }
        });
        pnlOkMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlOkMainMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlOkMainMousePressed(evt);
            }
        });

        lblOkMain.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblOkMain.setForeground(new java.awt.Color(255, 255, 255));
        lblOkMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOkMain.setText("OK");

        javax.swing.GroupLayout pnlOkMainLayout = new javax.swing.GroupLayout(pnlOkMain);
        pnlOkMain.setLayout(pnlOkMainLayout);
        pnlOkMainLayout.setHorizontalGroup(
            pnlOkMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOkMain, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        pnlOkMainLayout.setVerticalGroup(
            pnlOkMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOkMain, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlViewMain, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(pnlOkMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlViewMain, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlOkMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlOkMainMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlOkMainMouseMoved
        // TODO add your handling code here:
        pnlOkMain.setBackground(Signin.MOUSE_MOVED_BTN_COLOR);
    }//GEN-LAST:event_pnlOkMainMouseMoved

    private void pnlOkMainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlOkMainMousePressed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_pnlOkMainMousePressed

    private void pnlOkMainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlOkMainMouseExited
        // TODO add your handling code here:
        pnlOkMain.setBackground(Signin.MOUSE_EXITED_BTN_COLOR);
    }//GEN-LAST:event_pnlOkMainMouseExited

    public void showDialog() {
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - getWidth()) / 2;
        final int y = (screenSize.height - getHeight()) / 2;
        setLocation(x, y);
        setVisible(true);
        setLocationRelativeTo(null);
    }
    
    private void setData() {
        String listErrors = "";
        for(int i = 0; i < errors.size(); i++) {
            listErrors += errors.get(i) + "\n";
        }
        txtListErrorViewMain.setText(listErrors);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblErrorViewMain;
    private javax.swing.JLabel lblOkMain;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlOkMain;
    private javax.swing.JPanel pnlViewMain;
    private javax.swing.JScrollPane scrListErrorViewMain;
    private javax.swing.JTextArea txtListErrorViewMain;
    // End of variables declaration//GEN-END:variables
}
