/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.quanghuyabc9.GUI;

import com.quanghuyabc9.DTO.Person;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author quanghuyabc9
 */
public class PersonDialog extends javax.swing.JDialog {
    
    public static final Color MOUSE_MOVED_PNL_COLOR = new Color(129,131,185);
    public static final Color MOUSE_EXITED_PNL_COLOR = new Color(255,255,255);

    private static Person person;
    private static int request;
    public static final int SIGNOUT_REQUEST = 1;
    public static final int PROFILE_REQUEST = 2;
    
    public PersonDialog(java.awt.Frame parent, boolean modal, Person _person) {
        super(parent, modal);
        person = _person;
        request = 0;
        initComponents();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlFullname = new javax.swing.JPanel();
        lblFullname = new javax.swing.JLabel();
        pnlProfile = new javax.swing.JPanel();
        lblProfile = new javax.swing.JLabel();
        pnlSignout = new javax.swing.JPanel();
        lblSignout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Infor");
        setResizable(false);

        pnlMain.setBackground(new java.awt.Color(237, 235, 233));

        pnlFullname.setBackground(new java.awt.Color(255, 255, 255));

        lblFullname.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblFullname.setForeground(new java.awt.Color(51, 51, 51));
        lblFullname.setText("Username");
        lblFullname.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));

        javax.swing.GroupLayout pnlFullnameLayout = new javax.swing.GroupLayout(pnlFullname);
        pnlFullname.setLayout(pnlFullnameLayout);
        pnlFullnameLayout.setHorizontalGroup(
            pnlFullnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFullname, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
        );
        pnlFullnameLayout.setVerticalGroup(
            pnlFullnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFullname, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlProfile.setBackground(new java.awt.Color(255, 255, 255));
        pnlProfile.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlProfileMouseMoved(evt);
            }
        });
        pnlProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlProfileMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlProfileMousePressed(evt);
            }
        });

        lblProfile.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblProfile.setForeground(new java.awt.Color(51, 51, 51));
        lblProfile.setText("Profile");
        lblProfile.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));

        javax.swing.GroupLayout pnlProfileLayout = new javax.swing.GroupLayout(pnlProfile);
        pnlProfile.setLayout(pnlProfileLayout);
        pnlProfileLayout.setHorizontalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlProfileLayout.setVerticalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlSignout.setBackground(new java.awt.Color(255, 255, 255));
        pnlSignout.setPreferredSize(new java.awt.Dimension(78, 48));
        pnlSignout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlSignoutMouseMoved(evt);
            }
        });
        pnlSignout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSignoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlSignoutMousePressed(evt);
            }
        });

        lblSignout.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSignout.setForeground(new java.awt.Color(51, 51, 51));
        lblSignout.setText("Sign out");
        lblSignout.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));

        javax.swing.GroupLayout pnlSignoutLayout = new javax.swing.GroupLayout(pnlSignout);
        pnlSignout.setLayout(pnlSignoutLayout);
        pnlSignoutLayout.setHorizontalGroup(
            pnlSignoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSignout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSignoutLayout.setVerticalGroup(
            pnlSignoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSignout, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFullname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSignout, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlFullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSignout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlMainLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pnlProfile, pnlSignout});

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlProfileMouseExited
        // TODO add your handling code here:
        pnlProfile.setBackground(MOUSE_EXITED_PNL_COLOR);
    }//GEN-LAST:event_pnlProfileMouseExited

    private void pnlProfileMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlProfileMouseMoved
        // TODO add your handling code here:
        pnlProfile.setBackground(MOUSE_MOVED_PNL_COLOR);
    }//GEN-LAST:event_pnlProfileMouseMoved

    private void pnlSignoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSignoutMouseExited
        // TODO add your handling code here:
        pnlSignout.setBackground(MOUSE_EXITED_PNL_COLOR);
    }//GEN-LAST:event_pnlSignoutMouseExited

    private void pnlSignoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSignoutMouseMoved
        // TODO add your handling code here:
        pnlSignout.setBackground(MOUSE_MOVED_PNL_COLOR);
    }//GEN-LAST:event_pnlSignoutMouseMoved

    private void pnlSignoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSignoutMousePressed
        // TODO add your handling code here:
        request = SIGNOUT_REQUEST;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_pnlSignoutMousePressed

    private void pnlProfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlProfileMousePressed
        // TODO add your handling code here:
        request = PROFILE_REQUEST;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_pnlProfileMousePressed


    public int showDialog() {
        String fullname = person.getFullname();
        lblFullname.setText(fullname);
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - getWidth()) / 2;
        final int y = (screenSize.height - getHeight()) / 2;
        setLocation(x, y);
        setVisible(true);
        setLocationRelativeTo(null);
        return request;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFullname;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblSignout;
    private javax.swing.JPanel pnlFullname;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlProfile;
    private javax.swing.JPanel pnlSignout;
    // End of variables declaration//GEN-END:variables
}
