/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.quanghuyabc9.GUI;

import com.quanghuyabc9.BUS.PersonBUS;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author quanghuyabc9
 */
public class Signin extends javax.swing.JDialog {

    public Signin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public static final Color MOUSE_MOVED_BTN_COLOR = new Color(44, 151, 75);
    public static final Color MOUSE_EXITED_BTN_COLOR = new Color(46, 164, 79);
    public static final Color MOUSE_MOVED_BTN_COLOR_2 = new Color(237, 235, 233);
    public static final Color MOUSE_EXITED_BTN_COLOR_2 = new Color(255, 255, 255);

    private boolean isSigninSuccess = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlContent = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        psswrdPassword = new javax.swing.JPasswordField();
        btnSignin = new javax.swing.JButton();
        btnSignup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sign in to Conferences Management");
        setResizable(false);

        pnlMain.setBackground(new java.awt.Color(237, 235, 233));
        pnlMain.setLayout(new java.awt.GridBagLayout());

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setPreferredSize(new java.awt.Dimension(300, 350));

        txtUsername.setBackground(new java.awt.Color(243, 242, 241));
        txtUsername.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(51, 51, 51));
        txtUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));

        lblTitle.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(70, 71, 117));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Conferences Mangement");

        lblUsername.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(51, 51, 51));
        lblUsername.setText("Username");

        lblPassword.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(51, 51, 51));
        lblPassword.setText("Password");

        psswrdPassword.setBackground(new java.awt.Color(243, 242, 241));
        psswrdPassword.setForeground(new java.awt.Color(51, 51, 51));
        psswrdPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        psswrdPassword.setPreferredSize(new java.awt.Dimension(21, 19));

        btnSignin.setBackground(new java.awt.Color(46, 164, 79));
        btnSignin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSignin.setForeground(new java.awt.Color(255, 255, 255));
        btnSignin.setText("Sign in");
        btnSignin.setBorder(null);
        btnSignin.setFocusPainted(false);
        btnSignin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSigninMouseMoved(evt);
            }
        });
        btnSignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSigninMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSigninMousePressed(evt);
            }
        });

        btnSignup.setBackground(new java.awt.Color(255, 255, 255));
        btnSignup.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(150, 150, 192));
        btnSignup.setText("New user? Sign up");
        btnSignup.setBorder(null);
        btnSignup.setFocusPainted(false);
        btnSignup.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSignupMouseMoved(evt);
            }
        });
        btnSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignupMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSignupMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblUsername)
                        .addComponent(lblPassword)
                        .addComponent(txtUsername)
                        .addComponent(psswrdPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSignin, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                    .addComponent(btnSignup))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContentLayout.createSequentialGroup()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(psswrdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSignin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );

        pnlMain.add(pnlContent, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSigninMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSigninMouseMoved
        // TODO add your handling code here:
        btnSignin.setBackground(MOUSE_MOVED_BTN_COLOR);
    }//GEN-LAST:event_btnSigninMouseMoved

    private void btnSigninMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSigninMouseExited
        // TODO add your handling code here:
        btnSignin.setBackground(MOUSE_EXITED_BTN_COLOR);
    }//GEN-LAST:event_btnSigninMouseExited

    private void btnSigninMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSigninMousePressed
        // TODO add your handling code here:
        String username = txtUsername.getText().trim();
        String password = psswrdPassword.getText();
        List<String> errors = new ArrayList<>();
        boolean isSuccess = PersonBUS.authenticate(username, password, errors);
        if (isSuccess) {
            isSigninSuccess = isSuccess;
            setVisible(false);
            dispose();
        } else {
            Error dialog = new Error(new javax.swing.JFrame(), true, errors);
            dialog.showDialog();
        }
    }//GEN-LAST:event_btnSigninMousePressed

    private void btnSignupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMousePressed
        // TODO add your handling code here:
        Signup dialog = new Signup(new javax.swing.JFrame(), true);
        String[] userData = dialog.showDialog();
        String username = userData[0];
        String password = userData[1];
        if (username != null && password != null) {
            txtUsername.setText(username);
            psswrdPassword.setText(password);
        }
    }//GEN-LAST:event_btnSignupMousePressed

    private void btnSignupMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMouseMoved
        // TODO add your handling code here:
        btnSignup.setBackground(MOUSE_MOVED_BTN_COLOR_2);
    }//GEN-LAST:event_btnSignupMouseMoved

    private void btnSignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMouseExited
        // TODO add your handling code here:
        btnSignup.setBackground(MOUSE_EXITED_BTN_COLOR_2);
    }//GEN-LAST:event_btnSignupMouseExited

    public boolean showDialog() {
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - getWidth()) / 2;
        final int y = (screenSize.height - getHeight()) / 2;
        setLocation(x, y);
        setVisible(true);
        setLocationRelativeTo(null);
        return isSigninSuccess;
    }

    public void setData(String username, String password) {
        txtUsername.setText(username);
        psswrdPassword.setText(password);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignin;
    private javax.swing.JButton btnSignup;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPasswordField psswrdPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
