/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.quanghuyabc9.GUI;

import com.quanghuyabc9.BUS.PersonBUS;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author quanghuyabc9
 */
public class Signup extends javax.swing.JDialog {

    public Signup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    private String savedUsername = null;
    private String savedPassword = null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlContent = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblFullname = new javax.swing.JLabel();
        txtFullname = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        psswrdPassWord = new javax.swing.JPasswordField();
        lblPasswordAgain = new javax.swing.JLabel();
        psswrdPasswordAgain = new javax.swing.JPasswordField();
        btnSignup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sign up");
        setResizable(false);

        pnlMain.setBackground(new java.awt.Color(237, 235, 233));
        pnlMain.setPreferredSize(new java.awt.Dimension(500, 700));
        pnlMain.setLayout(new java.awt.GridBagLayout());

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setPreferredSize(new java.awt.Dimension(300, 550));

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(70, 71, 117));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("<html>Sign up for <br/> Conferences Mangement</html>");

        lblFullname.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblFullname.setForeground(new java.awt.Color(51, 51, 51));
        lblFullname.setText("Fullname");

        txtFullname.setBackground(new java.awt.Color(243, 242, 241));
        txtFullname.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtFullname.setForeground(new java.awt.Color(51, 51, 51));
        txtFullname.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));

        lblEmail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(51, 51, 51));
        lblEmail.setText("Email");

        txtEmail.setBackground(new java.awt.Color(243, 242, 241));
        txtEmail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(51, 51, 51));
        txtEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));

        lblUsername.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(51, 51, 51));
        lblUsername.setText("Username");

        txtUsername.setBackground(new java.awt.Color(243, 242, 241));
        txtUsername.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(51, 51, 51));
        txtUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));

        lblPassword.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(51, 51, 51));
        lblPassword.setText("Password");

        psswrdPassWord.setBackground(new java.awt.Color(243, 242, 241));
        psswrdPassWord.setForeground(new java.awt.Color(51, 51, 51));
        psswrdPassWord.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        psswrdPassWord.setPreferredSize(new java.awt.Dimension(21, 19));

        lblPasswordAgain.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPasswordAgain.setForeground(new java.awt.Color(51, 51, 51));
        lblPasswordAgain.setText("Enter password again");

        psswrdPasswordAgain.setEditable(false);
        psswrdPasswordAgain.setBackground(new java.awt.Color(243, 242, 241));
        psswrdPasswordAgain.setForeground(new java.awt.Color(51, 51, 51));
        psswrdPasswordAgain.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        psswrdPasswordAgain.setPreferredSize(new java.awt.Dimension(21, 19));

        btnSignup.setBackground(new java.awt.Color(46, 164, 79));
        btnSignup.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup.setText("Sign up");
        btnSignup.setBorder(null);
        btnSignup.setFocusPainted(false);
        btnSignup.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSignupMouseMoved(evt);
            }
        });
        btnSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignupMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSignupMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(psswrdPasswordAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPasswordAgain)
                    .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblFullname)
                        .addComponent(lblEmail)
                        .addComponent(txtFullname)
                        .addComponent(btnSignup, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                        .addComponent(lblUsername)
                        .addComponent(psswrdPassWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPassword)
                        .addComponent(txtEmail)
                        .addComponent(txtUsername)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(lblTitle)
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContentLayout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFullname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(psswrdPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPasswordAgain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(psswrdPasswordAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        psswrdPassWord.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                change();
            }
            public void removeUpdate(DocumentEvent e) {
                change();
            }
            public void insertUpdate(DocumentEvent e) {
                change();
            }

            public void change() {
                if(psswrdPassWord.getText().length() == 0)
                psswrdPasswordAgain.setEditable(false);
                else
                psswrdPasswordAgain.setEditable(true);
            }
        });

        pnlMain.add(pnlContent, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMousePressed
        // TODO add your handling code here:
        String fullname = txtFullname.getText();
        String email = txtEmail.getText();
        String username = txtUsername.getText();
        String password = psswrdPassWord.getText();
        String passwordAgain = psswrdPasswordAgain.getText();
        List<String> errors = new ArrayList<>();
        boolean isSuccess = PersonBUS.add(fullname, email, username, password, passwordAgain, errors);
        if(isSuccess) {
            savedUsername = username;
            savedPassword = password;
            setVisible(false);
            dispose();
        } else {
             Error dialog = new Error(new javax.swing.JFrame(), true, errors);
             dialog.showDialog();
        }                
    }//GEN-LAST:event_btnSignupMousePressed

    private void btnSignupMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMouseMoved
        // TODO add your handling code here:
         btnSignup.setBackground(Signin.MOUSE_MOVED_BTN_COLOR);
    }//GEN-LAST:event_btnSignupMouseMoved

    private void btnSignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMouseExited
        // TODO add your handling code here:
         btnSignup.setBackground(Signin.MOUSE_EXITED_BTN_COLOR);
    }//GEN-LAST:event_btnSignupMouseExited

    public String[] showDialog() {
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - getWidth()) / 2;
        final int y = (screenSize.height - getHeight()) / 2;
        setLocation(x, y);
        setVisible(true);
        setLocationRelativeTo(null);
        return new String[] {savedUsername, savedPassword};
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignup;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullname;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordAgain;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPasswordField psswrdPassWord;
    private javax.swing.JPasswordField psswrdPasswordAgain;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
