/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.quanghuyabc9.GUI.Management;

import com.quanghuyabc9.BUS.PersonBUS;
import com.quanghuyabc9.DTO.Person;
import com.quanghuyabc9.GUI.Guess;
import java.awt.Color;

/**
 *
 * @author quanghuyabc9
 */
public class _PersonItem extends javax.swing.JPanel {

    public static final int STATE_BLOCKED = 0;
    public static final int STATE_ACTIVE = 1;

    private Person person;
    private int state;

    public _PersonItem(Person _person) {
        person = _person;
        state = person.getAccessibleApp();
        initComponents();
        setData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblIdValue = new javax.swing.JLabel();
        lblUsernameValue = new javax.swing.JLabel();
        lblFullnameValue = new javax.swing.JLabel();
        lblEmailValue = new javax.swing.JLabel();
        pnlState = new javax.swing.JPanel();
        lblStateValue = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 25, 5, 10));
        setPreferredSize(new java.awt.Dimension(621, 50));
        setLayout(new java.awt.GridBagLayout());

        lblIdValue.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblIdValue.setForeground(new java.awt.Color(51, 51, 51));
        lblIdValue.setText("ID value");
        lblIdValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 5));
        lblIdValue.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        add(lblIdValue, gridBagConstraints);

        lblUsernameValue.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblUsernameValue.setForeground(new java.awt.Color(51, 51, 51));
        lblUsernameValue.setText("Username value");
        lblUsernameValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 5));
        lblUsernameValue.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(lblUsernameValue, gridBagConstraints);

        lblFullnameValue.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblFullnameValue.setForeground(new java.awt.Color(51, 51, 51));
        lblFullnameValue.setText("Fullname value");
        lblFullnameValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 5));
        lblFullnameValue.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(lblFullnameValue, gridBagConstraints);

        lblEmailValue.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEmailValue.setForeground(new java.awt.Color(51, 51, 51));
        lblEmailValue.setText("Email value");
        lblEmailValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 5));
        lblEmailValue.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(lblEmailValue, gridBagConstraints);

        pnlState.setBackground(new java.awt.Color(255, 255, 255));
        pnlState.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(223, 220, 230), 2, true));
        pnlState.setPreferredSize(new java.awt.Dimension(0, 0));
        pnlState.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlStateMouseMoved(evt);
            }
        });
        pnlState.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlStateMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlStateMousePressed(evt);
            }
        });
        pnlState.setLayout(new java.awt.BorderLayout());

        lblStateValue.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblStateValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStateValue.setText("Active or Blocked");
        lblStateValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnlState.add(lblStateValue, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        add(pnlState, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlStateMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlStateMouseMoved
        // TODO add your handling code here:
        pnlState.setBackground(Guess.MOUSE_MOVED_PNL_COLOR);
    }//GEN-LAST:event_pnlStateMouseMoved

    private void pnlStateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlStateMouseExited
        // TODO add your handling code here:
        pnlState.setBackground(Guess.MOUSE_EXITED_PNL_COLOR_3);
    }//GEN-LAST:event_pnlStateMouseExited

    private void pnlStateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlStateMousePressed
        // TODO add your handling code here:
        if (state == STATE_BLOCKED) {
            state = STATE_ACTIVE;
            lblStateValue.setForeground(Color.green);
            lblStateValue.setText("Active");
            person.setAccessibleApp(state);
            PersonBUS.update(person);
        } else if (state == STATE_ACTIVE) {
            state = STATE_BLOCKED;
            lblStateValue.setForeground(Color.red);
            lblStateValue.setText("Blocked");
            person.setAccessibleApp(state);
            PersonBUS.update(person);
        }
    }//GEN-LAST:event_pnlStateMousePressed

    private void setData() {
        lblIdValue.setText(String.valueOf(person.getId()));
        lblUsernameValue.setText(person.getUsername());
        lblFullnameValue.setText(person.getFullname());
        lblEmailValue.setText(person.getEmail());
        if (state == STATE_BLOCKED) {
            lblStateValue.setForeground(Color.red);
            lblStateValue.setText("Blocked");
        } else {
            lblStateValue.setForeground(Color.green);
            lblStateValue.setText("Active");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblEmailValue;
    private javax.swing.JLabel lblFullnameValue;
    private javax.swing.JLabel lblIdValue;
    private javax.swing.JLabel lblStateValue;
    private javax.swing.JLabel lblUsernameValue;
    private javax.swing.JPanel pnlState;
    // End of variables declaration//GEN-END:variables

}
