/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.quanghuyabc9.GUI.Management;

import com.quanghuyabc9.DTO.Conference;

/**
 *
 * @author quanghuyabc9
 */
public class UserEnrolledConference extends javax.swing.JPanel {

    private int index;
    private Conference conference;
    public UserEnrolledConference(int _index, Conference _conference) {
        conference = _conference;
        index = _index;
        initComponents();
        setData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblNumericalOrder = new javax.swing.JLabel();
        lblNameValue = new javax.swing.JLabel();

        setBackground(new java.awt.Color(243, 242, 241));
        setPreferredSize(new java.awt.Dimension(400, 50));
        setLayout(new java.awt.GridBagLayout());

        lblNumericalOrder.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNumericalOrder.setForeground(new java.awt.Color(51, 51, 51));
        lblNumericalOrder.setText("Numerical order");
        lblNumericalOrder.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.05;
        gridBagConstraints.weighty = 1.0;
        add(lblNumericalOrder, gridBagConstraints);

        lblNameValue.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNameValue.setForeground(new java.awt.Color(51, 51, 51));
        lblNameValue.setText("Name value");
        lblNameValue.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(lblNameValue, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void setData() {
        lblNumericalOrder.setText(String.valueOf(index));
        lblNameValue.setText(conference.getNameConference() + " (" + conference.getLocation().toString() + ")");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNameValue;
    private javax.swing.JLabel lblNumericalOrder;
    // End of variables declaration//GEN-END:variables
}
